package noergler

import leo.datastructures.TPTP
import leo.modules.input.TPTPParser

import java.io.FileNotFoundException
import java.util.logging.{ConsoleHandler, Level, Logger}
import java.nio.file.{InvalidPathException, Path}

object Noergler {
  final val name: String = "noergler"
  final val version: String = "0.1"

  private[this] final val logger: Logger = Logger.getLogger("Nörgler")
  private[this] var inputProblemName: Option[String] = None
  private[this] var inputProofName: String = ""
  private[this] var parameters: Seq[ProofCheckController.Parameter] = Seq.empty
  private[this] var verbosity: Level = Level.INFO
  private[this] val tptpHomeDirectory: Option[String] = sys.env.get("TPTP")

  final def main(args: Array[String]): Unit = {
    if (args.contains("--help")) {
      usage(); return
    }
    if (args.contains("--version")) {
      printVersion(); return
    }
    if (args.isEmpty) usage()
    else {
      var error: Option[String] = None
      var problemFileParsed = false // only purpose is to differentiate between the two input files
      // if parse errors happen

      try {
        parseArgs(args.toSeq)
        // logging crap
        System.setProperty("java.util.logging.SimpleFormatter.format",
          "[%4$s] %3$s: %5$s%6$s%n")
        logger.setLevel(verbosity)
        logger.setUseParentHandlers(false)
        val ch = new ConsoleHandler
        ch.setLevel(Level.ALL)
        logger.addHandler(ch)
        logger.fine(s"Nörgler started.")
        // Read input
        val (problemPath, problem): (Option[Path], Option[TPTP.Problem]) = if (inputProblemName.isDefined) {
          val problemPath0 = Path.of(inputProblemName.get).toAbsolutePath
          // Parse input problem
          (Some(problemPath0),Some(parseTPTPFile(problemPath0)))
        } else (None, None)
        problemFileParsed = true
        val proofPath = Path.of(inputProofName).toAbsolutePath
        // Parse input proof
        val proof: TPTP.Problem = parseTPTPFile(proofPath)
        // Call checker controller
        val result: Result = ProofCheckController.apply(problemPath, proofPath, problem, proof, parameters)
        // Generate SZS result
        val reporting: String = {
          result match {
            case Verified => generateSZSResult("status", "Verified", "", "", withPrefix = true)
            case FailedVerified(reason) => generateSZSResult("status", "FailedVerified", "", "", withPrefix = true, extraTSTPMessage = reason)
            case NotVerified(reason) => generateSZSResult("status", "NotVerified", "", "", withPrefix = true, extraTSTPMessage = reason)
          }
        }
        println(reporting)
        System.exit(0) // to make sure threads are killed etc.
      } catch {
        case e: IllegalArgumentException =>
          error = Some(e.getMessage)
        case e: FileNotFoundException =>
          error = Some(s"File cannot be found or is not readable/writable: ${e.getMessage}")
        case e: TPTPParser.TPTPParseException =>
          error = Some(s"${if (problemFileParsed) "Proof" else "Problem"} file could not be parsed, parse error at ${e.line}:${e.offset}: ${e.getMessage}")
        case e: Throwable =>
          error = Some(s"Unexpected error: ${e.getMessage} (${e.printStackTrace()}). This is considered an implementation error; please report this!")
      } finally {
        if (error.nonEmpty) {
          if (inputProblemName.nonEmpty) println(s"% SZS status Error for $inputProblemName : ${error.get}\n")
          else println(s"% SZS status Error : ${error.get}\n")
        }
        if (error.nonEmpty) System.exit(1)
      }
    }
  }

  private[this] def parseTPTPFile(path: Path): TPTP.Problem = {
    if (tptpHomeDirectory.isDefined) leo.modules.tptputils.parseTPTPFileWithIncludes(path, tptpHomeDirectory) else leo.modules.tptputils.parseTPTPFileWithoutIncludes(path)
  }

  private final def generateSZSResult(szsWord: String, szsStatus: String, result: String, szsDatatype: String, withPrefix: Boolean, extraTSTPMessage: String = "") = {
    import java.util.Calendar

    val sb: StringBuilder = new StringBuilder()
    if (withPrefix) {
      sb.append(s"%%% This output was generated by $name, version $version.\n")
      sb.append(s"%%% Generated on ${Calendar.getInstance().getTime.toString} using parameters '${parameters.map(_.toString).mkString(", ").toLowerCase}'.\n")
    }
    sb.append(generateSZSStatus(szsWord, szsStatus, extraTSTPMessage))
    sb.append(generateSZSOutput(result, szsDatatype))
    sb.toString()
  }
  private[this] final def generateSZSStatus(szsWord: String, szsStatus: String, extraTSTPMessage: String = ""): String = {
    if (extraTSTPMessage == null || extraTSTPMessage.isEmpty) s"% SZS $szsWord $szsStatus for $inputProofName\n"
    else s"% SZS $szsWord $szsStatus for $inputProofName : $extraTSTPMessage\n"
  }
  private[this] final def generateSZSOutput(result: String, szsDatatype: String): String = {
    val sb: StringBuilder = new StringBuilder()
    if (result.nonEmpty) {
      sb.append(s"% SZS output start $szsDatatype for $inputProofName\n")
      if (result.nonEmpty) sb.append(result)
      sb.append("\n")
      sb.append(s"% SZS output end $szsDatatype for $inputProofName\n")
    }
    sb.toString()
  }

  private[this] final def printVersion(): Unit = {
    println(s"$name $version")
  }

  private[this] final def usage(): Unit = {
    println(s"usage: $name [options] [--problem <problem file>] <proof file>")
    println(
      s"""
         | Nörgler is a proof checker for proofs from automated theorem provers
         | in the TSTP format from the TPTP infrastructure. Currently, only
         | checking of refutational FOF proofs is supported.
         |
         | The proof is supplied in <proof file>. If a <problem file> is also provided,
         | Nörgler will verify the proof relative to the problem's axioms and conjecture.
         |
         | Nörgler will always check the following structural and logical properties:
         |   - Uniqueness of formula names
         |   - Conclusion of proof with $$false
         |   - Acyclicity of inference parent graph (from $$false upward)
         |   - Existence of inference parents in each proof step earlier in proof
         |   - Correctness of Skolemization steps wrt. simple internal skolemization procedure
         |   - Provability of thm/cth steps in proof using external provers
         |
         | If a <problem file> is provided, Nörgler additionally checks:
         |   - Correctness of copies of axioms/conjecture from problem file
         |   - Correctness of negation of conjecture
         |
         | If one of these steps fail with an error, Nörgler will return SZS status
         | FailedVerified.
         | If one of these steps time out (most likely the check of provability of thm/cth steps)
         | SZS status NotVerified is returned.
         | The former SZS status claims that the proof is incorrect, while the latter status
         | does not make any claims with regard to correctness.
         |
         | Options:
         |  --timeout t      Timeout after n seconds (soft limit, best effort).
         |                   A timeout will result in a SZS status NotVerified output.
         |
         |  --prover name(s) Select the prover(s) to use for verifying thm/cth steps.
         |                   Options: 'eprover', 'vampire', 'all' (use all available),
         |                   or a comma-separated list (e.g., 'eprover,vampire').
         |                   If multiple provers are given and no parallelization
         |                   strategy running multiple provers at once is given,
         |                   the provers are tried in the sequence they are provided in.
         |                   Otherwise, they are run in parallel.
         |
         |  --eprover-path path
         |                  Path to eprover, if not findable by `which eprover`.
         |
         |  --vampire-path path
         |                  Path to vampire, if not findable by `which vampire`.
         |
         |  --model-finder  Select the model finder to be used. If not parallelization
         |                  mode is set, any model finder chosen here will onl be run
         |                  if the given prover(s) are not successful in finding a solution.
         |                  Options:'vampire'
         |
         |  --parallel-mode mode Set the parallelization strategy.
         |                  Options:
         |                     - none: Sequential execution (default).
         |                     - steps: Verify different proof steps in parallel.
         |                     - provers: Run multiple provers on the same step in parallel.
         |                     - hybrid: Parallelize both steps and provers.
         |
         |  --parallel-countermodel-mode
         |                  Options:
         |                     - none: Countermodel finder used only used as a fallback after
         |                       all chosen provers failed to find a solution
         |                     - always: Always also run counter model finder in parallel to provers
         |                       when running generic inference checks.
         |                     - offset: start countermodel-finder in parallel after running
         |                       provers without success for 1 second.
         |
         |  --verbosity n   Set the verbosity of logging to std.err. If n = 0, logging is disabled;
         |                  n = 6 is maximal verbosity (very fine-grained logging output).
         |
         |  --version       Print the version number of the executable and terminate.
         |
         |  --help          Print this description and terminate.
         |
         |  --up-to-esa     If set, Nörgler will not attempt to verify ESA steps (including Skolemization).
         |                  Recommended for provers that do not follow to precise Skolemization annotation format.
         |
         |  --relax-annotation-format
         |                  If set, Nörgler will be more permissive about the format of the formula annotation
         |                  as long as parent-child relationships can still be inferred. In particular, Nörgler will
         |                  i) allow nested application of inferences in annotations
         |                  ii) allow negation of the conjecture with inference names other than negated_conjecture, as
         |                      long as the status of the inference is cth, and the step has role "negated_conjecture"
         |
         |  --relax-problem-check
         |                  If set, Nörgler will be more permissive about the relationship between formulas from problem
         |                  files and their copies in the given proofs. In particular, Nörgler will
         |                  i) allow formulas with different roles
         |
         |  --relax-specified-inference-checks
         |                  Effects those steps derived by inferences with specified inference rules that trigger
         |                  checks via comparison to internally derived results (currently negate3d_conjecture
         |                  and Skolemization). If set, Nörgler will test if the step of the proof is derivable from the
         |                  internally produced version, as a fallback if formulas are not identical.
         |
         |  --allow-prover-axioms
         |                  If set, Nörgler will allow axioms with an annotation other than file, but print a warning
         |                  indicating that an axiom was introduced. Recommended for provers that introduce built-in
         |                  theory axioms.
         |""".stripMargin)
  }

  //todo: other potential model finders: princess, metis, fest, alloy, Nitpick, kodkod

  private[this] final def parseArgs(args: Seq[String]): Unit = {
    var args0 = args
    try {
      var hd = args0.head
      while (hd.startsWith("--")) { // Optional flags
        hd match {
          case "--problem" =>
            val path = args0.tail.head
            inputProblemName = Some(path)
            args0 = args0.tail
          case "--timeout" =>
            val to = args0.tail.head
            parameters = parameters :+ ProofCheckController.Timeout(to.toInt)
            args0 = args0.tail
          case "--prover" =>
            val input = args0.tail.head
            // Logic: Handle 'all', then split by comma and trim whitespace
            val selectedProvers = if (input == "all") {
              List("eprover", "vampire")
            } else {
              input.split(",").map(_.trim).toList
            }
            parameters = parameters :+ ProofCheckController.ProverSelection(selectedProvers)
            args0 = args0.tail
          case "--eprover-path" =>
            val path = args0.tail.head
            parameters = parameters :+ ProofCheckController.EproverPath(Path.of(path))
            args0 = args0.tail
          case "--model-finder" =>
            val input = args0.tail.head
            // Logic: Handle 'all', then split by comma and trim whitespace
            val selectedModelFinders = if (input == "all") {
              List("vampire")
            } else {
              input.split(",").map(_.trim).toList
            }
            parameters = parameters :+ ProofCheckController.ModelFinderSelection(selectedModelFinders)
            args0 = args0.tail
          case "--vampire-path" =>
            val path = args0.tail.head
            parameters = parameters :+ ProofCheckController.VampirePath(Path.of(path))
            args0 = args0.tail
          case "--parallel-mode" =>
            val mode = args0.tail.head
            val validModes = Set("none", "steps", "provers", "hybrid")
            if (!validModes.contains(mode)) {
              throw new IllegalArgumentException(s"Invalid parallel-mode '$mode'. Must be one of: ${validModes.mkString(", ")}")
            }
            parameters = parameters :+ ProofCheckController.SetParallelMode(mode)
            args0 = args0.tail
          case "--parallel-countermodel-mode" =>
            val mode = args0.tail.head
            val validModes = Set("none", "always", "offest")
            if (!validModes.contains(mode)) {
              throw new IllegalArgumentException(s"Invalid parallel-countermodel-mode '$mode'. Must be one of: ${validModes.mkString(", ")}")
            }
            parameters = parameters :+ ProofCheckController.SetParallelCountermodelMode(mode)
            args0 = args0.tail
          case "--verbosity" =>
            val arg = args0.tail.head.toInt
            val level = arg match {
              case _ if arg <= 0  => Level.OFF
              case 1 => Level.SEVERE
              case 2 => Level.INFO
              case 3 => Level.CONFIG
              case 4 => Level.FINE
              case 5 => Level.FINER
              case _ if arg >= 6 => Level.FINEST
            }
            verbosity = level
            args0 = args0.tail
          case "--relax-annotation-format" =>
            parameters = parameters :+ ProofCheckController.RelaxAnnotationFormat
          case "--relax-problem-check" =>
            parameters = parameters :+ ProofCheckController.RelaxProblemCheck
          case "--relax-specified-inference-checks" =>
            parameters = parameters :+ ProofCheckController.RelaxSpecifiedInferenceCheck
          case "--allow-prover-axioms" =>
            parameters = parameters :+ ProofCheckController.AllowProverAxioms
          case "--up-to-esa" =>
            parameters = parameters :+ ProofCheckController.UpToESA

          case _ => throw new IllegalArgumentException(s"Unknown parameter '$hd'.")
        }
        args0 = args0.tail
        hd = args0.head
      }
      // main arguments
      inputProofName = args0.head
      args0 = args0.tail
      if (args0.nonEmpty) {
        throw new IllegalArgumentException(s"Superfluous arguments supplied: '${args0.toString()}'")
      }
    } catch {
      case _:NoSuchElementException | _:ArrayIndexOutOfBoundsException | _:NumberFormatException =>
        throw new IllegalArgumentException(s"Not enough or illegal arguments supplied: ${args.toString()}")
      case e:InvalidPathException =>
        throw new IllegalArgumentException(s"Supplied path invalid: ${e.toString}")
    }
  }
}
